/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17326.group6.view;

import com.poly.it17326.group6.service.ForgotPassword;
import com.poly.it17326.group6.service.impl.ForgotPasswordServiceImpl;
import jakarta.mail.Authenticator;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tung Anh
 */
public class FormForgotPassword extends javax.swing.JFrame {

    private ForgotPassword fp = new ForgotPasswordServiceImpl();

    /**
     * Creates new form FormForgotPassword
     */
    public FormForgotPassword() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadIcon();
        this.setTitle("Forgot Password");
        // this.setLocation(420, 100);
        this.setLocationRelativeTo(null);
    }

    private void loadIcon() {
        txt_Email.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_ConfirmPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_ID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_NewPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_Verification.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    Random rd = new Random();
    int idVerifi = rd.nextInt(899999) + 100000;

    public String sendEmail(String id, String email) throws MessagingException, UnsupportedEncodingException {

        //Email gửi đi
        String fromEmail = "anhnttph23200@fpt.edu.vn";

        //Password của email
        String passwordEmail = "aqfwxdeeyauyvpqk";

        //Email người nhận
        String toEmail = email;

        //Tiêu đề email
        String subject = "Cửa hàng bán sữa";

        //Nội dung
        String body = "Test";

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        Authenticator authenticator = new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, passwordEmail);
            }
        };
        Session session = Session.getInstance(props, authenticator);
        MimeMessage message = new MimeMessage(session);

        message.addHeader("Content-type", "Text/HTML; charset=UTF-8");
        message.addHeader("format", "flowed");
        message.addHeader("Content-Transfer-Encoding", "8bit");
        message.setFrom(new InternetAddress(fromEmail, "FORGOT PASSWORD"));
        message.setReplyTo(InternetAddress.parse(fromEmail, false));
        message.setSubject(subject, "UTF-8");
        message.setText("Verification password: " + idVerifi, "UTF-8");
        message.setSentDate(new Date());
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));

        Transport.send(message);
        return "Send email successfully, please check your email!";
    }

    public void check() {
        if (txt_ID.getText().isBlank() || txt_Email.getText().isBlank()) {
            jlb_Email.setText("Not be empty!");
            jlb_Email.setForeground(Color.red);
            jlb_ID.setText("Not be empty!");
            jlb_ID.setForeground(Color.red);
        }
        if (!txt_ID.getText().isBlank() || !txt_Email.getText().isBlank()) {
            jlb_Email.setText("");
            jlb_Email.setForeground(Color.WHITE);
            jlb_ID.setText("");
            jlb_ID.setForeground(Color.white);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlb_NewPassword = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btn_Accept = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Verification = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_SendVerification = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_NewPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jlb_ConfirmPassword = new javax.swing.JLabel();
        jlb_Email = new javax.swing.JLabel();
        jlb_Verification2 = new javax.swing.JLabel();
        jlb_ID = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_NewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jlb_NewPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 552, -1, -1));

        btnback.setBackground(new java.awt.Color(153, 0, 0));
        btnback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Quay lại");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 90, 30));

        btn_Accept.setBackground(new java.awt.Color(153, 0, 0));
        btn_Accept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_Accept.setText("Xác nhận");
        btn_Accept.setBorder(null);
        btn_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AcceptActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Quên mật khẩu");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel8.setText("____________________________________________");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 340, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        txt_ID.setFont(txt_ID.getFont());
        txt_ID.setBorder(null);
        txt_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 300, -1));

        jLabel10.setText("___________________________________________");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 320, 30));

        txt_Email.setBorder(null);
        txt_Email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 302, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 37, -1));

        jLabel11.setText("___________________________________________");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 330, 30));

        txt_Verification.setBorder(null);
        txt_Verification.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txt_Verification, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 299, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mã xác nhận");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, -1));

        btn_SendVerification.setBackground(new java.awt.Color(153, 0, 0));
        btn_SendVerification.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_SendVerification.setForeground(new java.awt.Color(255, 255, 255));
        btn_SendVerification.setText("Gửi mã");
        btn_SendVerification.setBorder(null);
        btn_SendVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendVerificationActionPerformed(evt);
            }
        });
        jPanel2.add(btn_SendVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 30));

        jLabel12.setText("___________________________________________");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 330, 30));

        txt_NewPassword.setBorder(null);
        txt_NewPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txt_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 307, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mật khẩu mới");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 20));

        jLabel13.setText("___________________________________________");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 330, 30));

        txt_ConfirmPassword.setBorder(null);
        jPanel2.add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 310, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Xác nhận mật khẩu");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 447, -1, 30));
        jPanel2.add(jlb_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 190, 30));
        jPanel2.add(jlb_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 200, 30));
        jPanel2.add(jlb_Verification2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 180, 30));
        jPanel2.add(jlb_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 200, 30));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SendVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendVerificationActionPerformed
        this.check();
        try {
            JOptionPane.showMessageDialog(this, sendEmail(txt_ID.getText(), txt_Email.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_btn_SendVerificationActionPerformed

    private void btn_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcceptActionPerformed
        check();
        int verifi = Integer.parseInt(txt_Verification.getText());
        String verifi2 = txt_Verification.getText();
        String newPassword1 = String.valueOf(txt_NewPassword.getPassword());
        String confirmPassword = String.valueOf(txt_ConfirmPassword.getPassword());
        String ma = txt_ID.getText();
        this.check();

        try {
            //Check Send email
            if (verifi != idVerifi) {
                jlb_ConfirmPassword.setText("Verification is wrong, please check again!");
                jlb_ConfirmPassword.setForeground(Color.red);
            }
            if (verifi == idVerifi) {
                jlb_ConfirmPassword.setText("");
            }
            if (verifi2.isBlank()) {
                jlb_ConfirmPassword.setText("Not be empty!");
                jlb_ConfirmPassword.setForeground(Color.red);
            }
            if (!verifi2.isBlank()) {
                jlb_ConfirmPassword.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

//        if (newPassword1.isBlank()) {
//            jlb_NewPassword.setText("Not be empty!");
//            jlb_NewPassword.setForeground(Color.red);
//        }
//        if (!newPassword1.isBlank()) {
//            jlb_NewPassword.setText("");
//        }
//        if (confirmPassword.isBlank()) {
//            jlb_ConfirmPassword.setText("Not be empty!");
//            jlb_ConfirmPassword.setForeground(Color.red);
//        }
//        if (!confirmPassword.isBlank()) {
//            jlb_ConfirmPassword.setText("");
//        }
        if (!newPassword1.equals(confirmPassword)) {
            jlb_ConfirmPassword.setText("Confirm password isn't like New password!");
            jlb_ConfirmPassword.setForeground(Color.red);
        } else {
            Date now = new Date();
            fp.changePassword(ma, newPassword1, now);

            JOptionPane.showMessageDialog(this, "Change password successfully!");
        }

        if (!newPassword1.equals(confirmPassword)) {
            jlb_ConfirmPassword.setText("");
        }
    }//GEN-LAST:event_btn_AcceptActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accept;
    private javax.swing.JButton btn_SendVerification;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlb_ConfirmPassword;
    private javax.swing.JLabel jlb_Email;
    private javax.swing.JLabel jlb_ID;
    private javax.swing.JLabel jlb_NewPassword;
    private javax.swing.JLabel jlb_Verification2;
    private javax.swing.JPasswordField txt_ConfirmPassword;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JPasswordField txt_NewPassword;
    private javax.swing.JTextField txt_Verification;
    // End of variables declaration//GEN-END:variables
}
