/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17326.group6.view;

import com.poly.it17326.group6.domainmodel.TaiKhoan;
import com.poly.it17326.group6.service.ChangePasswordService;
import com.poly.it17326.group6.service.impl.ChangePasswordImpl;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Tung Anh
 */
public class FormChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form FormChangePassword
     */
    private ChangePasswordService changePasswordService = new ChangePasswordImpl();

    public FormChangePassword() {
        initComponents();
        Toolkit.getDefaultToolkit().getScreenSize();
        this.setTitle("Change Password");
        //this.setLocation(420, 100);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadIcon(){
        txt_OldPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_ConfirmPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_ID.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_NewPassword.setBackground(new java.awt.Color(0, 0, 0, 1));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_OldPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txt_ConfirmPassword = new javax.swing.JPasswordField();
        txt_NewPassword = new javax.swing.JPasswordField();
        txt_ID = new javax.swing.JTextField();
        btn_Back = new javax.swing.JButton();
        btn_Accept = new javax.swing.JButton();
        jlb_ConfirmPassword = new javax.swing.JLabel();
        jlb_OldPassword1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel10.setText("___________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thay đổi mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(151, 23, 8));
        jLabel7.setText("Mã nhân viên:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(151, 23, 8));
        jLabel4.setText("Mật khẩu cũ:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 143, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(151, 23, 8));
        jLabel5.setText("Mật khẩu mới:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 216, -1, -1));

        txt_OldPassword.setBorder(null);
        jPanel1.add(txt_OldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 176, 286, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(151, 23, 8));
        jLabel6.setText("Nhập lại mật khẩu:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 283, -1, -1));

        txt_ConfirmPassword.setBorder(null);
        jPanel1.add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 312, 285, -1));

        txt_NewPassword.setBorder(null);
        jPanel1.add(txt_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 243, 284, -1));

        txt_ID.setBorder(null);
        jPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 97, 285, -1));

        btn_Back.setBackground(new java.awt.Color(153, 0, 0));
        btn_Back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        btn_Back.setText("Quay lại");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 356, -1, -1));

        btn_Accept.setBackground(new java.awt.Color(153, 0, 0));
        btn_Accept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_Accept.setText("Xác nhận");
        btn_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AcceptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 356, -1, -1));
        jPanel1.add(jlb_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 233, 28));
        jPanel1.add(jlb_OldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 176, 219, 22));

        jLabel11.setText("___________________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, 20));

        jLabel12.setText("___________________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 320, 30));

        jLabel13.setText("___________________________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 320, 30));

        jLabel14.setText("___________________________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcceptActionPerformed
        String id = txt_ID.getText();
        String oldPass = String.valueOf(txt_OldPassword.getPassword());
        String newPass = String.valueOf(txt_NewPassword.getPassword());
        String confirmPass = String.valueOf(txt_ConfirmPassword.getPassword());
        if (changePasswordService.getPassword(id, oldPass)==null) {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại mã hoặc mật khẩu");
            return;
        } else {
            for (TaiKhoan tk : changePasswordService.getPassword(id, oldPass)) {
                if (tk.getMatKhau().equals(null)) {
                    jlb_ConfirmPassword.setText("Loi Password");
                    jlb_ConfirmPassword.setForeground(Color.red);
                }
                if (!oldPass.isBlank() || !confirmPass.isBlank()) {
                    if (!newPass.equals(confirmPass)) {
                        jlb_ConfirmPassword.setText("Confirm password isn't like New password!");
                        jlb_ConfirmPassword.setForeground(Color.red);
                    }
                    if (newPass.equals(confirmPass)) {
                        jlb_ConfirmPassword.setText("");

                        if (!id.isBlank() || !newPass.isBlank()) {
                            Date now = new Date();
                            changePasswordService.changePassword(id, newPass, now);
                            JOptionPane.showMessageDialog(this, "Successfully");
                        } else {
                            JOptionPane.showConfirmDialog(this, "ERROR");
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Please insert information");
                }
            }
        }
    }//GEN-LAST:event_btn_AcceptActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        FormMain main = new FormMain();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accept;
    private javax.swing.JButton btn_Back;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_ConfirmPassword;
    private javax.swing.JLabel jlb_OldPassword1;
    private javax.swing.JPasswordField txt_ConfirmPassword;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JPasswordField txt_NewPassword;
    private javax.swing.JPasswordField txt_OldPassword;
    // End of variables declaration//GEN-END:variables
}
